### ISSUE TITLE
The StackOverflow Problem

### ISSUE THREAD

**Issue by nahwneeth** [Sarthak-source/problems#1]
Add `print(distance)` before returning `distance` in `distancef`  
Add `print('new loop`)` after `for (var profile in profilelist)`  
keep the `!snapshot.hasData` condition that returns a progressIndicator.

```
distancef(var x, var y) async {
      var distance = await Geolocator().distanceBetween(
          profiles[await getcurrentuserindex(user.uid)].location.longitude,
          profiles[await getcurrentuserindex(user.uid)].location.latitude,
          x,
          y);
     
    print(distance); // add this
   return distance;
    }
```

```
for (var profile in profilelist) {

      print('new loop'); // add this

        double distance = await distancef(
            profile.location.latitude, profile.location.longitude);
        locationListWithDistance.add({
          'uid': profile.uid,
          'firstName': profile.firstName,
          'lastName': profile.lastName,
          'phoneNumber': profile.phoneNumber,
          'address': profile.address,
          'profilePic': profile.profilePic,
          'distance': distance,
        });
      }
```

```
builder: (context, snapshot) {
       // keep this condition, the sorted list has not returned yet
        if (!snapshot.hasData) {
          return CircularProgressIndicator();
        }

       // if the above statement is false then the sorted list has returned
        var sorted = snapshot.data as List<Map<String, dynamic>>; // extract sorted list

```

Tell me the output.
Any Leads?

**Comment by nahwneeth** [comment]
paste the debug output here

**Comment by Sarthak-source** [comment]
**Reload already in progress, ignoring request
Restarted application in 2,405ms.
D/ViewRootImpl@5b533e8[MainActivity]( 6140): ViewPostIme pointer 0
D/ViewRootImpl@5b533e8[MainActivity]( 6140): ViewPostIme pointer 1
I/flutter ( 6140): new loop
I/flutter ( 6140): 0.0
I/flutter ( 6140): new loop
I/flutter ( 6140): 13461288.0**

**Comment by Sarthak-source** [comment]
I think it **add()** which isn't working.

**Comment by nahwneeth** [comment]
Okay, try with the new condition, I did a dummy test and this should work

```
builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) { // try with this condition, this should work
          return CircularProgressIndicator();
        }

       // if the above statement is false then the sorted list has returned
        var sorted = snapshot.data as List<Map<String, dynamic>>; // extract sorted list

**Comment by Sarthak-source** [comment]
Now this is the output of debug console:-

**The following NoSuchMethodError was thrown building FutureBuilder<List<Map<String, dynamic>>>(dirty,
state: _FutureBuilderState<List<Map<String, dynamic>>>#ecb74):
The getter 'length' was called on null.
Receiver: null
Tried calling: length
The relevant error-causing widget was:
  FutureBuilder<List<Map<String, dynamic>>>**

Same as before. Looks like function returns an empty list.

**Comment by nahwneeth** [comment]
Bro check the condition, there is no `!` this time.

**Comment by Sarthak-source** [comment]
I've added`if (snapshot.connectionState == ConnectionState.waiting)` in place of `if (!snapshot.hasData)` and I get `CircularProgressIndicator()` for 2 mins and error get's displayed.

**Comment by nahwneeth** [comment]
try print LocationListWithDistance before returning

**Comment by nahwneeth** [comment]
So the new condition, doesn't show progressIndicator forever, so that solves one problem

**Comment by Sarthak-source** [comment]
**I/flutter ( 6140): []**

**Comment by nahwneeth** [comment]
try printing sorted. both should be same, because that's what we are returning

**Comment by Sarthak-source** [comment]
**D/ViewRootImpl@5b533e8[MainActivity]( 6140): ViewPostIme pointer 0
D/ViewRootImpl@5b533e8[MainActivity]( 6140): ViewPostIme pointer 1
I/flutter ( 6140): []
I/flutter ( 6140): new loop
I/flutter ( 6140): 0.0
I/flutter ( 6140): new loop
I/flutter ( 6140): 13461288.0
I/flutter ( 6140): null**

**Comment by nahwneeth** [comment]
no bro, print locationListWithDistance after sorting, that is after the for loop. you are printing before the loop. I want to see if the sorted list is being returned or null.

**Comment by nahwneeth** [comment]
Now that I look at it, you have used `.length` on `profiles` and not on `sorted`. The code that's in the github repository.

**Comment by Sarthak-source** [comment]
**I/flutter ( 6140): []
I/flutter ( 6140): new loop
I/flutter ( 6140): 0.0
I/flutter ( 6140): new loop
I/flutter ( 6140): 13461288.0
I/flutter ( 6140): [{uid: 7DZaHo1dZoSGkOxMSPJkJ9sGWe23, firstName: Khan , lastName: Noonien Singh , phoneNumber: 9876543210, address: Hi I'm from Earth
I/flutter ( 6140): I took part in Eugenics war
I/flutter ( 6140): and lost now I'm stranded on
I/flutter ( 6140): a planet
I/flutter ( 6140): And I'm  very disappointed
I/flutter ( 6140): it god and every he stands for
I/flutter ( 6140): I will destroy
I/flutter ( 6140): , profilePic: https://firebasestorage.googleapis.com/v0/b/comcrop-e4f36.appspot.com/o/unnamed.jpg?alt=media&token=d53e8f5f-3011-45cc-8835-5d63e6d2a2f8, distance: 0.0}, {uid: pku7MVdj1EOHWWSKl8ttpqCxoJQ2, firstName: Captian, lastName: Kirk, phoneNumber: 9087654321, address: Im captain of the starship enterprise and we boldly go where no man has gone before, profilePic: https://firebasestorage.googleapis.com/v0/b/comcrop-e4f36.appspot.com/o/IMG-20200727-WA0017.jpg?alt=media&token=7297ceb6-692c-4810-8334-3ecfab417c9a, distance: 13461288.0}]
I/flutter ( 6140): null**

**Comment by navaneethp123** [comment]
what is 
I/flutter ( 6140): []

**Comment by nahwneeth** [comment]
so, it's sorted, but not showing up in the future builder

**Comment by Sarthak-source** [comment]
Yeah.

**Comment by nahwneeth** [comment]
can you commit this code to github

**Comment by Sarthak-source** [comment]
I've never done it before how do I do it.

**Comment by nahwneeth** [comment]
okay before that try this: https://stackoverflow.com/a/55322176/13390651
```
switch (snapshot.connectionState) {
        case ConnectionState.none:
          return Text('Press button to start.');
        case ConnectionState.active:
        case ConnectionState.waiting:
          return Text('Awaiting result...');
        case ConnectionState.done:
          if (snapshot.hasError)
            return Text('Error: ${snapshot.error}');
          return Text('Result: ${snapshot.data}');
          // You can reach your snapshot.data['url'] in here
      }
      return null; // unreachable
```

**Comment by nahwneeth** [comment]
there is a edit button on the top right. click that, select everything and delete and then paste the new stuff and commit. (this is a hacky and fast way)

**Comment by Sarthak-source** [comment]
**Error:type 'double' is not a subtype of type 'int'** is on my device screen.

**Comment by nahwneeth** [comment]
lol... so stupid of us not to expect errors. Everything was working but there was error in datatype. thats why snapshot.data was returning null.

**Comment by nahwneeth** [comment]
```
  int d1 = a['distance'];
  int d2 = b['distance']
```
this is the only stuff i see as `int`, change them to `double` and try again.

**Comment by nahwneeth** [comment]
i'll be back in 10 min

**Comment by Sarthak-source** [comment]
Yes!, thanks dude without you I would have never got the answer in million years.

**Comment by nahwneeth** [comment]
R u getting the required output?

**Comment by nahwneeth** [comment]
happy fluttering!

**Comment by Sarthak-source** [comment]
> R u getting the required output?

Yeah
